language: c

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-dev
      - cmake

install:
  # Install yaml-cpp
  - CDIR=`pwd` : && YAML_CPP_VER=0.5.2
  - wget https://github.com/jbeder/yaml-cpp/archive/release-$YAML_CPP_VER.tar.gz -Oyaml-cpp-$YAML_CPP_VER.tar.gz
  - tar xvzf yaml-cpp-$YAML_CPP_VER.tar.gz
  - mkdir yaml-cpp-release-$YAML_CPP_VER/build && cd yaml-cpp-release-$YAML_CPP_VER/build
  - cmake -DCMAKE_INSTALL_PREFIX=$HOME/libs/yaml-cpp ..
  - make && make install
  - export PKG_CONFIG_PATH=$HOME/libs/yaml-cpp/lib/pkgconfig:$HOME/libs/yaml-cpp/share/pkgconfig
  - cd $CDIR

before_script:
  - PROJ_ROOT=`pwd`

script:
  - cd $PROJ_ROOT/ejercicio1 && ./bootstrap.sh && ./configure && make -j4
  - cd $PROJ_ROOT/ejercicio2 && ./bootstrap.sh && ./configure && make -j4
