language: c

before_install:
  - sudo add-apt-repository -y
      'deb http://gb.archive.ubuntu.com/ubuntu/ trusty universe'
  - sudo apt-get update

install:
  - sudo apt-get install -y libyaml-cpp-dev=0.5.1-1
  - sudo apt-get install -y libboost1.55-dev

script:
  - cd ejercicio1 && ./bootstrap.sh && ./configure && make -j4
