language: c

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-dev
      - libyaml-cpp-dev

# install:
#   # Install yaml-cpp 0.5.1
#   - CDIR=`pwd`
#   - wget https://github.com/jbeder/yaml-cpp/archive/release-0.5.1.tar.gz -Oyaml-cpp-0.5.1.tar.gz
#   - tar xvzf yaml-cpp-0.5.1.tar.gz
#   - mkdir yaml-cpp-release-0.5.1/build && cd yaml-cpp-release-0.5.1/build
#   - cmake -DCMAKE_INSTALL_PREFIX=$HOME/libs/yaml-cpp ..
#   - make && make install
#   - ls -R $HOME/libs/yaml-cpp
#   - export PKG_CONFIG_PATH=$HOME/libs/yaml-cpp/lib/pkgconfig:$HOME/libs/yaml-cpp/share/pkgconfig
#   - cd $CDIR

before_script:
  - PROJ_ROOT=`pwd`

script:
  - cd $PROJ_ROOT/ejercicio1 && ./bootstrap.sh && ./configure && make -j4
  - cd $PROJ_ROOT/ejercicio2 && ./bootstrap.sh && ./configure && make -j4 V=1
