language: c

# before_install:
#   - sudo add-apt-repository -y
#       'deb http://gb.archive.ubuntu.com/ubuntu/ trusty universe'
#   - sudo apt-get update

# install:
#   - sudo apt-get install -y libyaml-cpp-dev=0.5.1-1
#   - sudo apt-get install -y libboost1.55-dev

addons:
  apt:
    packages:
      - libboost1.55-dev

install:
  - CDIR=`pwd`
  - wget https://github.com/jbeder/yaml-cpp/archive/release-0.5.1.tar.gz -Oyaml-cpp-0.5.1.tar.gz
  - tar xvzf yaml-cpp-0.5.1.tar.gz
  - ls -l -R
#- libyaml-cpp-dev=0.5.1-1

before_script:
  - PROJ_ROOT=`pwd`

script:
  - cd $PROJ_ROOT/ejercicio1 && ./bootstrap.sh && ./configure && make -j4
  - cd $PROJ_ROOT/ejercicio2 && ./bootstrap.sh && ./configure && make -j4
